---
title: "Stock market analysis"
output: html_document
date: "2024-03-01"
---

## Introduction

In this project, we explore financial data from the stock market, particularly technology stocks. Financial data is an example of time series data, which is one of the most prevalent data types characterized by a series of data points indexed in time order. We will get the stock data from the Yahoo finance website, which is a rich resource for financial market data. By analyzing these data, we aim to answer the following questions:

-   What was the average change in prices of the stock over time?

-   What was the correlation between different stocks?

-   How can we predict the future stock price?

The last question is the most significant, but it is also the most difficult one. A good model would be helpful to assist future investments.

------------------------------------------------------------------------

## Getting the Data

To get the data from Yahoo Finance, we will be using [yfinance library](https://aroussi.com/post/python-yahoo-finance) which offers a programmatic way to download market data from Yahoo. Here, we load the four years history of stock prices of tech companies(Apple, Google, Microsoft and Amazon).

```{python}
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
plt.style.use("fivethirtyeight")

# For reading stock data from yahoo
from pandas_datareader.data import DataReader
import yfinance as yf
from pandas_datareader import data as pdr

yf.pdr_override()

# For time stamps
from datetime import datetime
```

```{python}
# The tech stocks we'll use for this analysis
tech_list = ['AAPL', 'GOOG', 'MSFT', 'AMZN']

# Set up End and Start times for data grab
end = datetime.now()
start = datetime(end.year - 4, end.month, end.day)

for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)
    

company_list = [AAPL, GOOG, MSFT, AMZN]
company_name = ["APPLE", "GOOGLE", "MICROSOFT", "AMAZON"]

for company, com_name in zip(company_list, company_name):
    company["company_name"] = com_name
    
df = pd.concat(company_list, axis=0)
```

## Data exploration

```{python}
df.info()
```

There is no missing value, and the data type of each columns are in the correct format. Let us now visualize the closing price over time, which is The last price at which the stock is traded during the regular trading day. A stock's closing price is the standard benchmark used by investors to track its performance over time.

```{python}
plt.figure(figsize=(15, 10))
plt.subplots_adjust(top=1.25, bottom=1.2)

for i, company in enumerate(company_list, 1):
    plt.subplot(2, 2, i)
    company['Adj Close'].plot()
    plt.ylabel('Adj Close')
    plt.xlabel(None)
    plt.title(f"Closing Price of {tech_list[i - 1]}")

plt.tight_layout()
plt.show()
```
